
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Debugger.Soft.Unity
{
	public partial class GeneralOptionsPanel
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.CheckButton buildCB;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Debugger.Soft.Unity.GeneralOptionsPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.Debugger.Soft.Unity.GeneralOptionsPanel";
			// Container child MonoDevelop.Debugger.Soft.Unity.GeneralOptionsPanel.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buildCB = new global::Gtk.CheckButton ();
			this.buildCB.CanFocus = true;
			this.buildCB.Name = "buildCB";
			this.buildCB.Label = global::Mono.Unix.Catalog.GetString ("_Build project in MonoDevelop");
			this.buildCB.DrawIndicator = true;
			this.buildCB.UseUnderline = true;
			this.vbox1.Add (this.buildCB);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buildCB]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
